name: Build
on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * *'
jobs:
  build:
    uses: generoi/github-action-update-plugins/.github/workflows/markup-update.yml@master
    with:
      slug: 'woocommerce-paytrail'
